import { SpatialNode, SensorTelemetry, AssetHealth, FieldWorker } from '../types/digitalTwin';
import { CompoundRiskAssessment } from '../types/compoundRisk';
import { WorkPermit } from '../types/permit';
import { RegulatoryStandard, CryptographicAuditEntry } from '../types/compliance';
import { HistoricalIncident } from '../types/incident';

export const MOCK_PLANT_NODES: SpatialNode[] = [
  { id: 'PLANT-01', name: 'Refinery Alpha (Gujarat Complex)', type: 'PLANT', coordinates: { x: 50, y: 50 }, status: 'CRITICAL' },
  { id: 'UNIT-HC2', name: 'Hydrocracker Unit 2', type: 'UNIT', parentId: 'PLANT-01', coordinates: { x: 30, y: 40 }, status: 'CRITICAL' },
  { id: 'ZONE-A1', name: 'Feed Distillation Area A1', type: 'ZONE', parentId: 'UNIT-HC2', coordinates: { x: 20, y: 25 }, status: 'SAFE' },
  { id: 'ZONE-B4', name: 'Reactor Feed & Compressor Zone B4', type: 'ZONE', parentId: 'UNIT-HC2', coordinates: { x: 55, y: 45 }, status: 'CRITICAL', zoneId: 'ZONE-B4' },
  { id: 'ZONE-C2', name: 'High-Pressure Separator Zone C2', type: 'ZONE', parentId: 'UNIT-HC2', coordinates: { x: 80, y: 70 }, status: 'WARNING', zoneId: 'ZONE-C2' },
];

export const MOCK_SENSORS: SensorTelemetry[] = [
  {
    sensorId: 'G-104',
    sensorName: 'LEL Gas Sensor B4-04',
    type: 'GAS_LEL',
    value: 22.4,
    unit: '% LEL',
    baselineMin: 0,
    baselineMax: 5,
    thresholdWarning: 10,
    thresholdCritical: 20,
    status: 'CRITICAL',
    lastUpdated: '10 seconds ago',
    zoneId: 'ZONE-B4',
    trend: 'RISING',
  },
  {
    sensorId: 'P-201',
    sensorName: 'Reactor Feed Pressure Transducer',
    type: 'PRESSURE',
    value: 142.8,
    unit: 'Bar',
    baselineMin: 110,
    baselineMax: 135,
    thresholdWarning: 138,
    thresholdCritical: 145,
    status: 'WARNING',
    lastUpdated: '5 seconds ago',
    zoneId: 'ZONE-B4',
    trend: 'RISING',
  },
  {
    sensorId: 'V-102',
    sensorName: 'Charge Pump P-102 Vibration Spectral Sensor',
    type: 'VIBRATION',
    value: 8.4,
    unit: 'mm/s',
    baselineMin: 0.5,
    baselineMax: 2.5,
    thresholdWarning: 4.5,
    thresholdCritical: 7.0,
    status: 'CRITICAL',
    lastUpdated: '2 seconds ago',
    zoneId: 'ZONE-B4',
    trend: 'RISING',
  },
  {
    sensorId: 'T-301',
    sensorName: 'Reactor Bed Temperature Sensor',
    type: 'TEMPERATURE',
    value: 388.5,
    unit: '°C',
    baselineMin: 320,
    baselineMax: 375,
    thresholdWarning: 380,
    thresholdCritical: 400,
    status: 'WARNING',
    lastUpdated: '12 seconds ago',
    zoneId: 'ZONE-B4',
    trend: 'STABLE',
  },
  {
    sensorId: 'G-101',
    sensorName: 'LEL Gas Sensor A1-01',
    type: 'GAS_LEL',
    value: 1.2,
    unit: '% LEL',
    baselineMin: 0,
    baselineMax: 5,
    thresholdWarning: 10,
    thresholdCritical: 20,
    status: 'SAFE',
    lastUpdated: '1 minute ago',
    zoneId: 'ZONE-A1',
    trend: 'STABLE',
  },
  {
    sensorId: 'G-108',
    sensorName: 'H2S Gas Sensor C2-02',
    type: 'GAS_LEL',
    value: 3.4,
    unit: 'PPM',
    baselineMin: 0,
    baselineMax: 5,
    thresholdWarning: 10,
    thresholdCritical: 15,
    status: 'SAFE',
    lastUpdated: '30 seconds ago',
    zoneId: 'ZONE-C2',
    trend: 'FALLING',
  },
];

export const MOCK_ASSETS: AssetHealth[] = [
  {
    assetId: 'PUMP-P102',
    name: 'Hydrocracker Feed Charge Pump P-102',
    category: 'PUMP',
    zoneId: 'ZONE-B4',
    status: 'CRITICAL',
    healthScore: 42,
    vibrationMmSec: 8.4,
    temperatureC: 84.2,
    operatingHours: 14200,
    lastMaintenance: '2026-05-10',
    activeWorkOrders: 2,
    rpm: 1425,
    torqueNm: 41.9,
    toolWearMin: 184,
    failureProbability: 88,
    remainingUsefulLife: 14,
    failureMode: 'Overstrain Failure (OSF)',
  },
  {
    assetId: 'REACTOR-R201',
    name: 'Primary Hydrocracking Reactor R-201',
    category: 'REACTOR',
    zoneId: 'ZONE-B4',
    status: 'WARNING',
    healthScore: 78,
    vibrationMmSec: 2.1,
    temperatureC: 388.5,
    operatingHours: 32000,
    lastMaintenance: '2026-01-15',
    activeWorkOrders: 1,
    rpm: 1780,
    torqueNm: 36.4,
    toolWearMin: 92,
    failureProbability: 22,
    remainingUsefulLife: 160,
    failureMode: null,
  },
  {
    assetId: 'EXCHANGER-E104',
    name: 'Effluent Heat Exchanger E-104',
    category: 'HEAT_EXCHANGER',
    zoneId: 'ZONE-A1',
    status: 'SAFE',
    healthScore: 96,
    vibrationMmSec: 0.8,
    temperatureC: 195.0,
    operatingHours: 8500,
    lastMaintenance: '2026-06-20',
    activeWorkOrders: 0,
  },
];

export const MOCK_WORKERS: FieldWorker[] = [
  {
    id: 'W-804',
    name: 'Vikram Sharma',
    role: 'Senior Maintenance Technician',
    zoneId: 'ZONE-B4',
    coordinates: { x: 58, y: 48 },
    shiftHoursActive: 10.8,
    ppeCompliant: true,
    certifications: ['Hot Work Authorized', 'Pressure System L2'],
    assignedPermitId: 'PTW-8409',
    vitalStatus: 'ELEVATED_HEART_RATE',
  },
  {
    id: 'W-809',
    name: 'Rajesh Kumar',
    role: 'Welding Specialist',
    zoneId: 'ZONE-B4',
    coordinates: { x: 56, y: 46 },
    shiftHoursActive: 11.2,
    ppeCompliant: true,
    certifications: ['Certified Pipe Welder Grade 1'],
    assignedPermitId: 'PTW-8409',
    vitalStatus: 'NORMAL',
  },
  {
    id: 'W-912',
    name: 'Amit Patel',
    role: 'Process Operator',
    zoneId: 'ZONE-A1',
    coordinates: { x: 22, y: 26 },
    shiftHoursActive: 4.5,
    ppeCompliant: true,
    certifications: ['DCS Operator', 'Emergency Isolation'],
    vitalStatus: 'NORMAL',
  },
];

export const MOCK_PERMITS: WorkPermit[] = [
  {
    permitId: 'PTW-2026-8409',
    applicantName: 'Vikram Sharma',
    applicantRole: 'Senior Maintenance Technician',
    department: 'Mechanical Maintenance',
    permitType: 'HOT_WORK',
    plantUnit: 'Hydrocracker Unit 2',
    zoneId: 'ZONE-B4',
    zoneName: 'Reactor Feed Area B4',
    startTime: '2026-07-22T17:00:00Z',
    endTime: '2026-07-22T21:00:00Z',
    durationHours: 4,
    description: 'Hot work flame cutting and welding on Charge Pump P-102 recirculation feed line flange.',
    supervisorName: 'Karan Mehta (Chief EHS Officer)',
    status: 'RECOMMENDED_REJECT',
    aiRiskScore: 96,
    aiRecommendation: 'REJECT',
    atmosphericTests: {
      lelGas: 22.4,
      o2Percentage: 20.8,
      h2sPpm: 1.2,
      testedBy: 'Field Sampling Sampler S-02',
      testTimestamp: '2026-07-22T16:50:00Z',
    },
    isolationLocks: [
      { lockId: 'LOTO-MECH-401', tagType: 'LOTO_MECHANICAL', location: 'Valve HV-102 Recirculation Line', verifiedBy: 'Rajesh Kumar', status: 'LOCKED_VERIFIED' },
      { lockId: 'LOTO-ELEC-902', tagType: 'LOTO_ELECTRICAL', location: 'Breaker MCC-B4-09 Pump P-102', verifiedBy: 'Amit Patel', status: 'PENDING_VERIFICATION' },
    ],
    associatedAssessmentId: 'CRA-2026-8409',
    safetyPrecautions: ['Continuous LEL monitoring mandatory', 'Dual fire watch deployed with 50lb CO2 extinguisher', 'Spark containment blanket installed'],
  },
  {
    permitId: 'PTW-2026-8410',
    applicantName: 'Sanjay Dutt',
    applicantRole: 'Vessel Inspection Engineer',
    department: 'Quality & Integrity',
    permitType: 'CONFINED_SPACE',
    plantUnit: 'Hydrocracker Unit 2',
    zoneId: 'ZONE-C2',
    zoneName: 'High-Pressure Separator Zone C2',
    startTime: '2026-07-23T08:00:00Z',
    endTime: '2026-07-23T14:00:00Z',
    durationHours: 6,
    description: 'Internal ultrasonic thickness inspection inside Vessel V-204.',
    supervisorName: 'Karan Mehta',
    status: 'PENDING_AI_REVIEW',
    aiRiskScore: 38,
    aiRecommendation: 'APPROVE_WITH_CONDITIONS',
    atmosphericTests: {
      lelGas: 0.0,
      o2Percentage: 20.9,
      h2sPpm: 0.0,
      testedBy: 'Safety Inspector S-04',
      testTimestamp: '2026-07-22T16:30:00Z',
    },
    isolationLocks: [
      { lockId: 'LOTO-VALVE-88', tagType: 'VALVE_BLIND', location: 'Vessel V-204 Inlet Flange Blind', verifiedBy: 'Sanjay Dutt', status: 'LOCKED_VERIFIED' },
    ],
    safetyPrecautions: ['Forced fresh air ventilation required', 'Standby attendant continuously logged'],
  },
];

export const MOCK_PRIMARY_ASSESSMENT: CompoundRiskAssessment = {
  assessmentId: 'CRA-2026-8409',
  timestamp: '2026-07-22T16:54:00Z',
  plantId: 'PLANT-01',
  unitName: 'Hydrocracker Unit 2',
  zoneId: 'ZONE-B4',
  zoneName: 'Reactor Feed Area B4',
  compoundRiskScore: 96,
  riskVelocity: +18.4,
  riskLevel: 'CRITICAL',
  confidenceScore: 0.94,
  targetEntity: {
    type: 'PERMIT_REQUEST',
    entityId: 'PTW-2026-8409',
    description: 'Hot Work Flame Cutting & Welding on Pump P-102 Feed Line',
  },
  fourQuestions: {
    whatIsHappening: 'Hot work welding requested on Pump P-102 while LEL gas levels are elevated (22.4%) and mechanical vibration indicates bearing seal breakdown.',
    whyIsItHappening: 'Flammable hydrocarbon vapor accumulation detected by Sensor G-104 overlapping spatially (<8 meters) with active Hot Work Permit PTW-8409 and 11th-hour crew fatigue.',
    howDangerousIsIt: 'CRITICAL (96% Compound Risk). Explosive ignition probability is high. Catastrophic vapor cloud explosion risk with potential loss of human life and multi-million dollar asset destruction.',
    whatShouldBeDone: [
      'IMMEDIATELY REJECT Hot Work Permit PTW-2026-8409 in the system.',
      'Halt all maintenance operations on Pump P-102 and evacuate non-essential crew from Zone B4.',
      'Dispatch Nitrogen Purge Protocol ISO-HC2-09 and initiate SCADA vapor dispersion ventilation.',
    ],
  },
  contributingFactors: [
    {
      agentName: 'SensorAgent',
      agentTitle: 'SCADA Telemetry Specialist',
      factorText: 'LEL Gas Sensor G-104 reading 22.4% LEL (Baseline <5%, Critical >20%)',
      metricValue: '22.4% LEL',
      baselineValue: '< 5% LEL',
      weight: 0.35,
      severity: 'CRITICAL',
    },
    {
      agentName: 'PermitAgent',
      agentTitle: 'Work Authorization Specialist',
      factorText: 'Hot Work Permit PTW-8409 requested within 8m radius of active gas leak',
      metricValue: 'Hot Work Active',
      weight: 0.28,
      severity: 'CRITICAL',
    },
    {
      agentName: 'MaintenanceAgent',
      agentTitle: 'Asset Integrity Specialist',
      factorText: 'Pump P-102 Spectral Vibration Spike (8.4 mm/s vs baseline 2.1 mm/s)',
      metricValue: '8.4 mm/s',
      baselineValue: '2.1 mm/s',
      weight: 0.16,
      severity: 'HIGH',
    },
    {
      agentName: 'ShiftAgent',
      agentTitle: 'Fatigue & Crew Analyst',
      factorText: 'Welding Team assigned (W-804 & W-809) in 11th hour of continuous shift',
      metricValue: '11.2 Shift Hours',
      baselineValue: '< 8 Hours',
      weight: 0.09,
      severity: 'WARNING',
    },
    {
      agentName: 'IncidentAgent',
      agentTitle: 'Historical Precedent Engine',
      factorText: '89% Similarity Match with 2021 Hydrocracker Explosion (INC-2021-04-12)',
      metricValue: '89% Vector Match',
      weight: 0.08,
      severity: 'HIGH',
    },
    {
      agentName: 'ComplianceAgent',
      agentTitle: 'Statutory Rule Guardrail',
      factorText: 'Direct Violation of OISD-STD-105 Section 6.2 (Hot Work Prohibition)',
      metricValue: 'OISD Violation',
      weight: 0.04,
      severity: 'CRITICAL',
    },
  ],
  regulatoryLineage: [
    'OISD-STD-105 (Work Permit System in Petroleum Refineries - Section 6.2)',
    'OSHA 1910.119(k) (Process Safety Management - Hot Work Permit Compliance)',
    'The Factories Act 1948 - Section 37 (Precautions against dangerous fumes & explosive gases)',
  ],
  historicalIncidentMatch: {
    incidentId: 'INC-2021-04-12',
    title: 'Hydrocracker Unit Vapor Cloud Explosion',
    similarityScore: 0.89,
    date: '12 April 2021',
    location: 'Refinery West (Jamnagar Complex)',
  },
  mitigations: [
    {
      step: 1,
      actionTitle: 'Reject Work Permit PTW-2026-8409',
      description: 'Block permit authorization in Nexora. Notify field supervisor immediately.',
      urgency: 'IMMEDIATE',
      automatedActionType: 'ONE_CLICK_REJECT',
      targetEntityId: 'PTW-2026-8409',
    },
    {
      step: 2,
      actionTitle: 'Dispatch Zone B4 Safety Alarm & Muster Alert',
      description: 'Trigger visual warning beacon in Zone B4 and notify Field Safety Officer Vikram Sharma.',
      urgency: 'IMMEDIATE',
      automatedActionType: 'DISPATCH_SAFETY_OFFICER',
      targetEntityId: 'ZONE-B4',
    },
    {
      step: 3,
      actionTitle: 'Initiate SCADA Vapor Dispersion Purge',
      description: 'Recommend SCADA activation of exhaust fans EV-401 & EV-402 to dilute LEL concentrations.',
      urgency: 'HIGH',
      automatedActionType: 'SCADA_ISOLATION_SUGGESTION',
      targetEntityId: 'PUMP-P102',
    },
  ],
  status: 'UNRESOLVED',
};

export const MOCK_REGULATORY_STANDARDS: RegulatoryStandard[] = [
  {
    code: 'OISD-STD-105',
    name: 'Work Permit System in Petroleum Industry',
    governingBody: 'Oil Industry Safety Directorate (India)',
    complianceScore: 92,
    totalRules: 48,
    activeViolations: 1,
    lastAuditDate: '2026-07-01',
  },
  {
    code: 'OSHA 1910.119',
    name: 'Process Safety Management of Highly Hazardous Chemicals',
    governingBody: 'Occupational Safety & Health Administration (USA)',
    complianceScore: 96,
    totalRules: 72,
    activeViolations: 0,
    lastAuditDate: '2026-06-15',
  },
  {
    code: 'ISO 45001',
    name: 'Occupational Health and Safety Management Systems',
    governingBody: 'International Organization for Standardization',
    complianceScore: 98,
    totalRules: 110,
    activeViolations: 0,
    lastAuditDate: '2026-05-30',
  },
];

export const MOCK_AUDIT_LOGS: CryptographicAuditEntry[] = [
  {
    entryId: 'AUD-88049',
    sequenceNumber: 14209,
    timestamp: '2026-07-22T16:54:12Z',
    actorId: 'AI-SUPERVISOR-01',
    actorName: 'Nexora AI Supervisor Engine',
    actorRole: 'AI Autonomous Intelligence',
    eventType: 'PERMIT_REJECTION',
    targetEntityId: 'PTW-2026-8409',
    actionSummary: 'Generated Critical Compound Risk Assessment (96%) and issued ONE-CLICK REJECT recommendation for Permit PTW-8409.',
    previousHash: 'a7f3e8b9104c2d6e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e',
    currentHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    digitalSignature: 'SIG-RSA4096-7781029384756',
  },
  {
    entryId: 'AUD-88048',
    sequenceNumber: 14208,
    timestamp: '2026-07-22T16:50:00Z',
    actorId: 'USR-1029',
    actorName: 'Vikram Sharma',
    actorRole: 'Senior Maintenance Technician',
    eventType: 'PERMIT_AUTHORIZATION',
    targetEntityId: 'PTW-2026-8409',
    actionSummary: 'Submitted Work Permit Request PTW-2026-8409 for Hot Work welding on Pump P-102 feed line.',
    previousHash: 'c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5',
    currentHash: 'a7f3e8b9104c2d6e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e',
    digitalSignature: 'SIG-RSA4096-1029384756123',
  },
];

export const MOCK_HISTORICAL_INCIDENTS: HistoricalIncident[] = [
  {
    incidentId: 'INC-2021-04-12',
    title: 'Hydrocracker Unit Vapor Cloud Explosion',
    date: '12 April 2021',
    plantLocation: 'Refinery West (Jamnagar Complex)',
    unit: 'Hydrocracker Unit 1',
    severity: 'CATASTROPHIC',
    summary: 'Ignition of flammable hydrocarbon vapor cloud released during hot work maintenance on recirculation pump seal flange under high ambient LEL conditions.',
    rootCauses: [
      'Inadequate gas testing prior to hot work authorization',
      'Undetected mechanical seal degradation on high-pressure pump P-101',
      'Failure to correlate atmospheric gas telemetry with active work permit zone',
    ],
    contributingFactors: [
      'Shift fatigue of maintenance crew (12th consecutive hour)',
      'Communication gap during shift handover',
    ],
    fatalities: 0,
    injuries: 3,
    financialLossUsd: 14200000,
    regulatoryViolations: ['OISD-STD-105 Sec 6.2', 'OSHA 1910.119(k)'],
    vectorEmbeddingTags: ['hydrocracker', 'hot work', 'gas leak', 'pump seal', 'vapor cloud explosion'],
    preventiveActionImplemented: [
      'Mandatory continuous LEL gas monitoring during welding',
      'Deployment of AI Compound Risk Intelligence overlay (Nexora platform specification)',
    ],
  },
];
